In [ ]:
import numpy as np
arr = np.array([1,2,3,4])
mylist = arr.tolist()
print(mylist)

[1, 2, 3, 4]


In [ ]:
import numpy as np
arr2 = np.array ([[0,1,2] ,[3,4,5] , [6,7,8]])
diagonal= np.trace(arr2)
print(diagonal)

12


In [ ]:
import numpy as np
arr3 = np.array([[1,2],[3,5]])
print(arr3[arr3>3])

[5]


In [ ]:
import numpy as np
a = np.array([[1,2],[3,5]])
b = np.array([[8,7],[6,4]])
c = np.add(a,b)
print(c)

[[9 9]
 [9 9]]


In [12]:
import numpy as np
d = np.array ([[0,1,2] ,[3,4,5] , [6,7,8]])
e = d - d.mean(axis=1)
print(e)

[[-1. -3. -5.]
 [ 2.  0. -2.]
 [ 5.  3.  1.]]
